using UnityEngine;

public class Bomb : MonoBehaviour
{

    [Header("Explosion Settings")]
    // public float delay = 2f;                // Th·ªùi gian n·ªï sau khi n√©m
    // public float explosionRadius = 2f;      // B√°n k√≠nh n·ªï
    // public int damage = 1;                 // S√°t th∆∞∆°ng
    // public GameObject explosionEffect;      // Prefab hi·ªáu ·ª©ng n·ªï

    public float lifeTime = 3f;

    private Rigidbody2D rb;
    private bool hasExploded = false;
    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        // rb = GetComponent<Rigidbody2D>();
        Destroy(gameObject, lifeTime);

    }

    // Update is called once per frame
    // void Update()
    // {

    // }

    private void OnCollisionEnter2D(Collision2D collision)
    {
        if (collision.gameObject.CompareTag("Ground"))
        {
            Debug.Log("üí• Bom ƒë√£ n·ªï khi ch·∫°m ƒë·∫•t!");
            Destroy(gameObject);
        }
    }
}
